name: Backend Production Deployment

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Backend image tag to deploy (e.g., be-dev-a1b2c, be-stag-x1y2z)'
        required: true
        type: string
      confirm_production:
        description: 'Type "PRODUCTION" to confirm deployment'
        required: true
        type: string

jobs:
  validate-and-deploy:
    name: Validate and Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_production }}" != "PRODUCTION" ]; then
          echo "Production deployment not confirmed. Please type 'PRODUCTION' to confirm."
          exit 1
        fi
        echo "Production deployment confirmed"

    - name: Validate image tag format
      run: |
        IMAGE_TAG="${{ github.event.inputs.image_tag }}"
        if [[ ! "$IMAGE_TAG" =~ ^be-(dev|stag|prod)-[a-zA-Z0-9]+$ ]]; then
          echo "Invalid image tag format. Expected: be-{env}-{version} (e.g., be-dev-a1b2c)"
          exit 1
        fi
        echo "Image tag format is valid: $IMAGE_TAG"

    - name: Update Helm Chart Repository
      run: |
        # Set image tag for deployment
        IMAGE_TAG="${{ github.event.inputs.image_tag }}"

        echo "Updating Helm Chart Repository with backend image tag: ${IMAGE_TAG}"

        # Clone helm chart repository
        git clone https://${{ secrets.HELM_CHAR_TOKEN }}@github.com/${{ secrets.HELM_CHART_USERNAME }}/${{ secrets.HELM_CHART_REPO }}.git
        cd ${{ secrets.HELM_CHART_REPO }}

        # Configure git
        git config user.email "${{ secrets.GIT_EMAIL }}"
        git config user.name "${{ secrets.GIT_USERNAME }}"

        # Update backend image tag in production values file
        if command -v yq &> /dev/null; then
          yq eval '.backend.image.tag = "'${IMAGE_TAG}'"' -i envs/prod/prod-values.yaml
        else
          # Fallback to sed if yq not available
          sed -i "s|tag:.*|tag: \"${IMAGE_TAG}\"|g" envs/prod/prod-values.yaml
        fi

        # Commit and push changes
        git add envs/prod/prod-values.yaml
        git commit -m "feat(backend): update production image tag to ${IMAGE_TAG} (manual deployment)"
        git push origin main

        echo "Successfully updated helm chart repository with backend image tag: ${IMAGE_TAG}"
