name: DCO Sign-off

on:
  pull_request_target:
    branches:
      - main
      - develop
      - staging
      - release/**
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
jobs:
  check:
    name: Check DCO Signed-off-by
    runs-on: ubuntu-latest
    steps:
      - uses: live627/check-pr-signoff-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
